name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test-setup-nextstrain-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/setup-nextstrain-cli
      - run: nextstrain version --verbose

  test-pathogen-repo-ci:
    uses: ./.github/workflows/pathogen-repo-ci.yaml
    with:
      repo: nextstrain/zika

  test-pathogen-repo-ci-no-example-data:
    uses: ./.github/workflows/pathogen-repo-ci.yaml
    with:
      repo: nextstrain/zika-tutorial
