name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test-setup-nextstrain-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/setup-nextstrain-cli
      - run: nextstrain version --verbose

  test-pathogen-repo-ci:
    uses: ./.github/workflows/pathogen-repo-ci.yaml
    with:
      repo: nextstrain/zika

  test-pathogen-repo-ci-no-example-data:
    uses: ./.github/workflows/pathogen-repo-ci.yaml
    with:
      repo: nextstrain/zika-tutorial

  test-docs-ci-conda:
    uses: ./.github/workflows/docs-ci.yaml
    with:
      repo: nextstrain/docs.nextstrain.org
      docs-directory: .
      environment-file: environment.yml

  test-docs-ci-pip:
    uses: ./.github/workflows/docs-ci.yaml
    with:
      repo: nextstrain/augur
      docs-directory: docs/
      pip-install-target: .[dev]

  test-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./devel/check-readme
