# This workflow is intended to be called by workflows in our various software
# repos containing Sphinx documentation projects.
# See workflow-templates/docs-ci.yaml (a "starter" workflow) in this repo for
# an example of what the caller workflow looks like.
name: Sphinx docs CI

on:
  workflow_call:
    inputs:
      docs-directory:
        description: >-
          Directory containing Makefile. (e.g. docs/)
        type: string
        required: true

      environment-file:
        description: >-
          Path to conda environment file (e.g. docs/conda.yml)
        type: string
        required: true

      make-target:
        description: >-
          Sphinx builder name. See https://www.sphinx-doc.org/en/master/man/sphinx-build.html#options
        type: string
        default: html

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: ${{ inputs.environment-file }}
    - run: conda list
    - run: make ${{ inputs.make-target }}
      working-directory: ${{ inputs.docs-directory }}
      env:
        # https://www.sphinx-doc.org/en/master/man/sphinx-build.html
        # -n: warn on missing references
        # -W: error on warnings
        # --keep-going: find all warnings
        SPHINXOPTS: -n -W --keep-going
