# This workflow is intended to be called by workflows in our various pathogen
# build repos.  See workflow-templates/pathogen-repo-ci.yaml (a "starter"
# workflow) in this repo for an example of what the caller workflow looks like.
name: CI

on:
  workflow_call:
    inputs:
      build-args:
        description: >-
          Additional command-line arguments to pass to `nextstrain build` after
          the build directory (e.g. to Snakemake).
        type: string
        default: ""
        required: false

      repo:
        description: >-
          Repository name with owner (e.g. nextstrain/zika).  Defaults to the
          repository of the caller workflow.
        type: string
        default: ${{ github.repository }}
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}

      # XXX TODO: It would be better for this to call setup-nextstrain-cli
      # using the same ref that this workflow was called with (e.g. if this
      # workflow was invoked by the caller workflow with @foo than we invoke
      # the action with @foo too), but it's not currently possible to figure
      # out that ref.  See discussion around this (including results of some
      # investigation I did):
      #
      #   - https://github.community/t/reusable-workflows-get-the-ref-inside-the-called-workflow/224109
      #   - https://github.community/t/ref-head-in-reusable-workflows/203690/92
      #
      # Once we can figure out that ref, then we can actions/checkout our
      # nextstrain/.github repo at that ref as a sidecar path somewhere and
      # then invoke the setup-nextstrain-cli action using a local file path
      # instead of a remote owner/repo path.  This separate checkout will be
      # necessary since the "uses:" key can't be interpolated (${{…}}) with
      # context vars.
      #
      # For now, update the hardcoded ref (e.g. @90af34…) below when you make
      # future changes to setup-nextstrain-cli.
      #
      #   -trs, 28 April 2022
      - uses: nextstrain/.github/actions/setup-nextstrain-cli@90af34a2feb76db3feb337b03faf1ae158fd5042
        with:
          # Consider parameterizing the Python version. -trs, 1 April 2022
          python-version: "3.7"

      - name: Copy example data
        run: |
          if [[ -d example_data ]]; then
            mkdir -p data/
            cp -v example_data/* data/
          else
            echo No example data to copy.
          fi

      - run: nextstrain build --docker . ${{ inputs.build-args }}

      - uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: |
            auspice/
            results/
            benchmarks/
            logs/
            .snakemake/log/
